name: Sync lockfile

on:
  workflow_dispatch:
  push:
    paths:
      - "package.json"
      - ".github/workflows/sync-lockfile.yml"

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # 生成/同步 package-lock.json
      - name: Install deps (generate lockfile)
        run: npm install --no-audit --no-fund

      # 仅当 lockfile 变更时提交
      - name: Commit lockfile if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync package-lock.json for Cloudflare Pages"
          file_pattern: "package-lock.json"
