name: Sync lockfile

on:
  workflow_dispatch:
  push:
    paths:
      - "package.json"
      - ".github/workflows/sync-lockfile.yml"

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # 重新生成锁文件（避免审计等耗时）
      - run: npm install --no-audit --no-fund

      #  用现成 Action 自动提交 package-lock.json 的变化
      - name: Commit lockfile if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: sync package-lock.json for Cloudflare Pages"
          file_pattern: "package-lock.json"
